# Generated by Django 4.2 on 2023-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_candidate_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interview", old_name="cv_file_path", new_name="zip_file_path",
        ),
        migrations.AddField(
            model_name="candidate",
            name="cv_file_path",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
