# Generated by Django 4.2 on 2023-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_cv_file_path_interview_zip_file_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinterview", name="access_control",),
        migrations.AddField(
            model_name="user",
            name="access_control",
            field=models.CharField(
                blank=True,
                choices=[("CL", "Client"), ("AG", "Agent"), ("CO", "My_Company")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="cv_file_path",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="interview",
            name="zip_file_path",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
