# Generated by Django 4.2 on 2023-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_category_candidate_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="cv_file_path",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
